run:
  timeout: 5m
  tests: true
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - bodyclose
    - misspell
issues:
  exclude-dirs:
    - internal/generated
    - internal/db
