// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_log (tenant_id, actor_id, action, target_type, target_id, request_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	TenantID   pgtype.UUID
	ActorID    pgtype.UUID
	Action     string
	TargetType string
	TargetID   pgtype.UUID
	RequestID  string
}

// queries/audit.sql
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.RequestID,
	)
	return err
}

const queryAuditLog = `-- name: QueryAuditLog :many
SELECT id, tenant_id, actor_id, action, target_type, target_id, request_id, occurred_at
FROM audit_log
WHERE action = $1
  AND ($2::uuid IS NULL OR actor_id = $2::uuid)
ORDER BY occurred_at DESC
LIMIT 50
`

type QueryAuditLogParams struct {
	Action  string
	ActorID pgtype.UUID
}

func (q *Queries) QueryAuditLog(ctx context.Context, arg QueryAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, queryAuditLog, arg.Action, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.RequestID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
