// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeCredentialToken = `-- name: ConsumeCredentialToken :one
UPDATE credential_tokens
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
RETURNING id
`

// Single-shot conditional consume: the row updates only when consumed_at is
// still null, so a replayed activate call (or a lost race with a concurrent
// one) matches no row and returns pgx.ErrNoRows rather than silently
// succeeding twice.
func (q *Queries) ConsumeCredentialToken(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeCredentialToken, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getCredentialTokenByHash = `-- name: GetCredentialTokenByHash :one
SELECT id, tenant_id, user_id, purpose, expires_at, consumed_at
FROM credential_tokens
WHERE token_hash = $1
LIMIT 1
`

type GetCredentialTokenByHashRow struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	UserID     pgtype.UUID
	Purpose    string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
}

// Resolves a token by its unique hash with NO tenant filter: credential_tokens
// carries no RLS policy, so this is a genuine service-global, pre-auth lookup
// (the same posture as GetActiveDEK on crypto_keys). Isolation is the token's
// 256-bit entropy, not a WHERE clause.
func (q *Queries) GetCredentialTokenByHash(ctx context.Context, tokenHash []byte) (GetCredentialTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getCredentialTokenByHash, tokenHash)
	var i GetCredentialTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const insertCredentialToken = `-- name: InsertCredentialToken :one

INSERT INTO credential_tokens (
    tenant_id, user_id, purpose, token_hash, expires_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, user_id, purpose, expires_at, consumed_at
`

type InsertCredentialTokenParams struct {
	TenantID  pgtype.UUID
	UserID    pgtype.UUID
	Purpose   string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type InsertCredentialTokenRow struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	UserID     pgtype.UUID
	Purpose    string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
}

// queries/credential_tokens.sql
// credential_tokens is service-global (no RLS); this write still runs inside
// WithTenant so it shares connection lifecycle discipline with the sibling
// user writes, though the GUC has no bearing on this table's visibility.
func (q *Queries) InsertCredentialToken(ctx context.Context, arg InsertCredentialTokenParams) (InsertCredentialTokenRow, error) {
	row := q.db.QueryRow(ctx, insertCredentialToken,
		arg.TenantID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i InsertCredentialTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const invalidateActivationTokensForUser = `-- name: InvalidateActivationTokensForUser :exec
UPDATE credential_tokens
SET consumed_at = now()
WHERE user_id = $1 AND purpose = 'activation' AND consumed_at IS NULL
`

// Marks every outstanding (unconsumed) activation token for the user
// consumed, so a fresh resend cannot be joined by a still-live prior link.
func (q *Queries) InvalidateActivationTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidateActivationTokensForUser, userID)
	return err
}
