// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIdempotentResponse = `-- name: GetIdempotentResponse :one

SELECT status_code, response_body FROM idempotency_keys
WHERE idem_key = $1 AND route = $2
`

type GetIdempotentResponseParams struct {
	IdemKey string
	Route   string
}

type GetIdempotentResponseRow struct {
	StatusCode   int32
	ResponseBody []byte
}

// queries/idempotency.sql
func (q *Queries) GetIdempotentResponse(ctx context.Context, arg GetIdempotentResponseParams) (GetIdempotentResponseRow, error) {
	row := q.db.QueryRow(ctx, getIdempotentResponse, arg.IdemKey, arg.Route)
	var i GetIdempotentResponseRow
	err := row.Scan(&i.StatusCode, &i.ResponseBody)
	return i, err
}

const saveIdempotentResponse = `-- name: SaveIdempotentResponse :exec
INSERT INTO idempotency_keys (tenant_id, idem_key, route, status_code, response_body)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, idem_key, route) DO NOTHING
`

type SaveIdempotentResponseParams struct {
	TenantID     pgtype.UUID
	IdemKey      string
	Route        string
	StatusCode   int32
	ResponseBody []byte
}

func (q *Queries) SaveIdempotentResponse(ctx context.Context, arg SaveIdempotentResponseParams) error {
	_, err := q.db.Exec(ctx, saveIdempotentResponse,
		arg.TenantID,
		arg.IdemKey,
		arg.Route,
		arg.StatusCode,
		arg.ResponseBody,
	)
	return err
}
