// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveDEK = `-- name: GetActiveDEK :one

SELECT wrapped_dek FROM crypto_keys
WHERE active = true
ORDER BY created_at DESC
LIMIT 1
`

// queries/keys.sql
func (q *Queries) GetActiveDEK(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getActiveDEK)
	var wrapped_dek []byte
	err := row.Scan(&wrapped_dek)
	return wrapped_dek, err
}

const insertDEK = `-- name: InsertDEK :one
INSERT INTO crypto_keys (wrapped_dek) VALUES ($1)
RETURNING id
`

func (q *Queries) InsertDEK(ctx context.Context, wrappedDek []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDEK, wrappedDek)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
