// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	ActorID    pgtype.UUID
	Action     string
	TargetType string
	TargetID   pgtype.UUID
	RequestID  string
	OccurredAt pgtype.Timestamptz
}

type CredentialToken struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	UserID     pgtype.UUID
	Purpose    string
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type CryptoKey struct {
	ID         pgtype.UUID
	WrappedDek []byte
	Active     bool
	CreatedAt  pgtype.Timestamptz
}

type IdempotencyKey struct {
	TenantID     pgtype.UUID
	IdemKey      string
	Route        string
	StatusCode   int32
	ResponseBody []byte
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	BranchID       pgtype.UUID
	EmailEncrypted []byte
	EmailHash      string
	PasswordHash   string
	DisplayName    string
	Role           string
	ProviderRole   string
	Status         string
	MfaEnrolled    bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	TotpSecret     []byte
	TotpLastStep   *int64
	PhoneEncrypted []byte
}
