// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Records the highest accepted TOTP time-step for a user, atomically rejecting a
	// replayed or older code: the row updates only when the new step is strictly
	// greater than the stored one (or none is stored yet), so a code from the same
	// or an earlier window matches no row (RFC 6238 section 5.2). Runs under RLS via
	// WithTenant, so it is scoped to the caller tenant exactly like the sibling TOTP
	// writes. Returns the user id only when a step was accepted.
	AcceptTotpStep(ctx context.Context, arg AcceptTotpStepParams) (pgtype.UUID, error)
	// queries/users.sql
	// Runs under RLS (app.tenant_id set by WithTenant), so only the caller tenant's
	// row is visible. email_hash is unique per tenant. LIMIT 1 is defensive: it
	// keeps the :one contract safe even if RLS were ever misconfigured. mfa_enrolled
	// is projected so login can decide whether to require a second factor.
	AuthByEmailHash(ctx context.Context, emailHash string) (AuthByEmailHashRow, error)
	// Clears the secret, unsets mfa_enrolled, and resets the replay step, returning
	// the user to the enrol-required state. Used by the super-admin reset. The last
	// accepted step is nulled too so a fresh re-enrolment starts with clean replay
	// state (a reset resets all TOTP state, not just the secret).
	ClearTotp(ctx context.Context, id pgtype.UUID) error
	// Counts live provider super-admins under the caller tenant (the platform
	// tenant, set by WithTenant). Used by the operator bootstrap to stay a safe
	// one-shot: it refuses to create a second operator once one exists.
	CountProviderSuperAdmins(ctx context.Context, providerRole string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// queries/keys.sql
	GetActiveDEK(ctx context.Context) ([]byte, error)
	// queries/idempotency.sql
	GetIdempotentResponse(ctx context.Context, arg GetIdempotentResponseParams) (GetIdempotentResponseRow, error)
	// Reads the encrypted TOTP secret and mfa_enrolled for a user by id, under RLS.
	// A null totp_secret means the user has not enrolled a secret.
	GetTotpSecret(ctx context.Context, id pgtype.UUID) (GetTotpSecretRow, error)
	GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error)
	// queries/audit.sql
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertDEK(ctx context.Context, wrappedDek []byte) (pgtype.UUID, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	QueryAuditLog(ctx context.Context, arg QueryAuditLogParams) ([]AuditLog, error)
	SaveIdempotentResponse(ctx context.Context, arg SaveIdempotentResponseParams) error
	// Flips mfa_enrolled, called on a confirmed enrolment.
	SetMfaEnrolled(ctx context.Context, arg SetMfaEnrolledParams) error
	// Stores the encrypted TOTP secret. It does NOT flip mfa_enrolled: enrolment
	// only completes once the user confirms a code, which calls SetMfaEnrolled.
	SetTotpSecret(ctx context.Context, arg SetTotpSecretParams) error
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
