// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptTotpStep = `-- name: AcceptTotpStep :one
UPDATE users
SET totp_last_step = $1::bigint, updated_at = now()
WHERE id = $2
    AND (totp_last_step IS NULL OR totp_last_step < $1::bigint)
RETURNING id
`

type AcceptTotpStepParams struct {
	Step int64
	ID   pgtype.UUID
}

// Records the highest accepted TOTP time-step for a user, atomically rejecting a
// replayed or older code: the row updates only when the new step is strictly
// greater than the stored one (or none is stored yet), so a code from the same
// or an earlier window matches no row (RFC 6238 section 5.2). Runs under RLS via
// WithTenant, so it is scoped to the caller tenant exactly like the sibling TOTP
// writes. Returns the user id only when a step was accepted.
func (q *Queries) AcceptTotpStep(ctx context.Context, arg AcceptTotpStepParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, acceptTotpStep, arg.Step, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const authByEmailHash = `-- name: AuthByEmailHash :one

SELECT id, tenant_id, branch_id, password_hash, role, provider_role, status,
    mfa_enrolled
FROM users
WHERE email_hash = $1
LIMIT 1
`

type AuthByEmailHashRow struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	BranchID     pgtype.UUID
	PasswordHash string
	Role         string
	ProviderRole string
	Status       string
	MfaEnrolled  bool
}

// queries/users.sql
// Runs under RLS (app.tenant_id set by WithTenant), so only the caller tenant's
// row is visible. email_hash is unique per tenant. LIMIT 1 is defensive: it
// keeps the :one contract safe even if RLS were ever misconfigured. mfa_enrolled
// is projected so login can decide whether to require a second factor.
func (q *Queries) AuthByEmailHash(ctx context.Context, emailHash string) (AuthByEmailHashRow, error) {
	row := q.db.QueryRow(ctx, authByEmailHash, emailHash)
	var i AuthByEmailHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.PasswordHash,
		&i.Role,
		&i.ProviderRole,
		&i.Status,
		&i.MfaEnrolled,
	)
	return i, err
}

const clearTotp = `-- name: ClearTotp :exec
UPDATE users
SET totp_secret = NULL, mfa_enrolled = false, totp_last_step = NULL,
    updated_at = now()
WHERE id = $1
`

// Clears the secret, unsets mfa_enrolled, and resets the replay step, returning
// the user to the enrol-required state. Used by the super-admin reset. The last
// accepted step is nulled too so a fresh re-enrolment starts with clean replay
// state (a reset resets all TOTP state, not just the secret).
func (q *Queries) ClearTotp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearTotp, id)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    tenant_id, branch_id, email_encrypted, email_hash, password_hash,
    display_name, role, provider_role
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, branch_id, email_encrypted, display_name, role,
    provider_role, status, mfa_enrolled, created_at, updated_at
`

type CreateUserParams struct {
	TenantID       pgtype.UUID
	BranchID       pgtype.UUID
	EmailEncrypted []byte
	EmailHash      string
	PasswordHash   string
	DisplayName    string
	Role           string
	ProviderRole   string
}

type CreateUserRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	BranchID       pgtype.UUID
	EmailEncrypted []byte
	DisplayName    string
	Role           string
	ProviderRole   string
	Status         string
	MfaEnrolled    bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.BranchID,
		arg.EmailEncrypted,
		arg.EmailHash,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
		arg.ProviderRole,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.EmailEncrypted,
		&i.DisplayName,
		&i.Role,
		&i.ProviderRole,
		&i.Status,
		&i.MfaEnrolled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotpSecret = `-- name: GetTotpSecret :one
SELECT totp_secret, mfa_enrolled
FROM users
WHERE id = $1
`

type GetTotpSecretRow struct {
	TotpSecret  []byte
	MfaEnrolled bool
}

// Reads the encrypted TOTP secret and mfa_enrolled for a user by id, under RLS.
// A null totp_secret means the user has not enrolled a secret.
func (q *Queries) GetTotpSecret(ctx context.Context, id pgtype.UUID) (GetTotpSecretRow, error) {
	row := q.db.QueryRow(ctx, getTotpSecret, id)
	var i GetTotpSecretRow
	err := row.Scan(&i.TotpSecret, &i.MfaEnrolled)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, branch_id, email_encrypted, display_name, role,
    provider_role, status, mfa_enrolled, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	BranchID       pgtype.UUID
	EmailEncrypted []byte
	DisplayName    string
	Role           string
	ProviderRole   string
	Status         string
	MfaEnrolled    bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.EmailEncrypted,
		&i.DisplayName,
		&i.Role,
		&i.ProviderRole,
		&i.Status,
		&i.MfaEnrolled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, branch_id, email_encrypted, display_name, role,
    provider_role, status, mfa_enrolled, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	BranchID       pgtype.UUID
	EmailEncrypted []byte
	DisplayName    string
	Role           string
	ProviderRole   string
	Status         string
	MfaEnrolled    bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.EmailEncrypted,
			&i.DisplayName,
			&i.Role,
			&i.ProviderRole,
			&i.Status,
			&i.MfaEnrolled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMfaEnrolled = `-- name: SetMfaEnrolled :exec
UPDATE users
SET mfa_enrolled = $2, updated_at = now()
WHERE id = $1
`

type SetMfaEnrolledParams struct {
	ID          pgtype.UUID
	MfaEnrolled bool
}

// Flips mfa_enrolled, called on a confirmed enrolment.
func (q *Queries) SetMfaEnrolled(ctx context.Context, arg SetMfaEnrolledParams) error {
	_, err := q.db.Exec(ctx, setMfaEnrolled, arg.ID, arg.MfaEnrolled)
	return err
}

const setTotpSecret = `-- name: SetTotpSecret :exec
UPDATE users
SET totp_secret = $2, updated_at = now()
WHERE id = $1
`

type SetTotpSecretParams struct {
	ID         pgtype.UUID
	TotpSecret []byte
}

// Stores the encrypted TOTP secret. It does NOT flip mfa_enrolled: enrolment
// only completes once the user confirms a code, which calls SetMfaEnrolled.
func (q *Queries) SetTotpSecret(ctx context.Context, arg SetTotpSecretParams) error {
	_, err := q.db.Exec(ctx, setTotpSecret, arg.ID, arg.TotpSecret)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET status = 'deleted', updated_at = now()
WHERE id = $1 AND status <> 'deleted'
RETURNING id
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = COALESCE($1, display_name),
    status       = COALESCE($2, status),
    updated_at   = now()
WHERE id = $3
RETURNING id, tenant_id, branch_id, email_encrypted, display_name, role,
    provider_role, status, mfa_enrolled, created_at, updated_at
`

type UpdateUserParams struct {
	DisplayName *string
	Status      *string
	ID          pgtype.UUID
}

type UpdateUserRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	BranchID       pgtype.UUID
	EmailEncrypted []byte
	DisplayName    string
	Role           string
	ProviderRole   string
	Status         string
	MfaEnrolled    bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.DisplayName, arg.Status, arg.ID)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.EmailEncrypted,
		&i.DisplayName,
		&i.Role,
		&i.ProviderRole,
		&i.Status,
		&i.MfaEnrolled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
